/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Pessoa;
import model.PessoaEmail;
import model.PessoaEndereco;
import model.PessoaTelefone;
import util.DB;
import util.Util;

/**
 *
 * @author Dinei A. Rockenbach
 */
public class PnlPessoa extends javax.swing.JPanel {

    private Pessoa pessoa;
    private ArrayList<PessoaEmail> lstPessoaEmail = new ArrayList<>();
    private ArrayList<PessoaTelefone> lstPessoaTelefone = new ArrayList<>();
    private ArrayList<PessoaEndereco> lstPessoaEndereco = new ArrayList<>();
    
    public PnlPessoa() {
        initComponents();
        
        Util.setLimitChars(txtNome, 150);
        Util.setLimitChars(txtCpfCnpj, 14);
        Util.setLimitChars(txtRG, 10);
        
    }
    public PnlPessoa(Pessoa pessoa) {
        this();
        setPessoa(pessoa);
    }

    public Pessoa getPessoa() {
        return pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
        if (pessoa.getFlag().equals(DB.FLAG_UPDATE)) {
            txtNome.setText(pessoa.getPesNome());
            txtDataNascimento.setText(Util.getFormattedDate(pessoa.getPesDtaNascimento()));
            if (pessoa.getPesSexo() != 0) {
                rdbMasculino.setSelected(pessoa.getPesSexo() == Pessoa.SEXO_MASCULINO);
                rdbFeminino.setSelected(pessoa.getPesSexo() == Pessoa.SEXO_FEMININO);
            }
            if (!pessoa.getPesTipoPessoa().equals("")) {
                rdbFisica.setSelected(pessoa.getPesTipoPessoa().equals(Pessoa.TIPO_FISICA));
                rdbJuridica.setSelected(pessoa.getPesTipoPessoa().equals(Pessoa.TIPO_JURIDICA));
            }
            shTipoPessoa();
            txtCpfCnpj.setText(pessoa.getPesCPFCNPJ());
            txtRG.setText(pessoa.getPesRG());
            
            lstPessoaEndereco = PessoaEndereco.getAll(pessoa);
            loadTblPessoaEndereco();
            
            lstPessoaTelefone = PessoaTelefone.getAll(pessoa);
            loadTblPessoaTelefone();
            
            lstPessoaEmail = PessoaEmail.getAll(pessoa);
            loadTblPessoaEmail();
        }
    }
    
    private void loadTblPessoaEndereco() {
        DefaultTableModel dtm = (DefaultTableModel) tblEndereco.getModel();
        dtm.setNumRows(0);
        for (PessoaEndereco pe : lstPessoaEndereco) {
            dtm.addRow(new Object[]{pe.getPesEndDescricao(), pe.toString(), pe});
        }
    }
    
    private void loadTblPessoaTelefone() {
        DefaultTableModel dtm = (DefaultTableModel) tblTelefone.getModel();
        dtm.setNumRows(0);
        for (PessoaTelefone pt : lstPessoaTelefone) {
            dtm.addRow(new Object[]{pt.getPesFonDescricao(), pt.getPesFonTelefone(), pt});
        }
    }
    
    private void loadTblPessoaEmail() {
        DefaultTableModel dtm = (DefaultTableModel) tblEmail.getModel();
        dtm.setNumRows(0);
        for (PessoaEmail pe : lstPessoaEmail) {
            dtm.addRow(new Object[]{pe.getPesEmlEmail(), pe});
        }
    }
    
    public void savePessoa() {
        if (pessoa == null) {
            pessoa = new Pessoa();
        }
        pessoa.setPesNome(txtNome.getText());
        pessoa.setPesDtaNascimento(Util.getDateFromString(txtDataNascimento.getText()));
        pessoa.setPesSexo((rdbMasculino.isSelected()) ? Pessoa.SEXO_MASCULINO : Pessoa.SEXO_FEMININO);
        pessoa.setPesTipoPessoa((rdbFisica.isSelected()) ? Pessoa.TIPO_FISICA : Pessoa.TIPO_JURIDICA);
        pessoa.setPesCPFCNPJ(txtCpfCnpj.getText());
        pessoa.setPesRG(txtRG.getText());
        
        pessoa.setPessoaEndereco(lstPessoaEndereco.toArray(new PessoaEndereco[lstPessoaEndereco.size()]));

        pessoa.setPessoaTelefone(lstPessoaTelefone.toArray(new PessoaTelefone[lstPessoaTelefone.size()]));
        
        pessoa.setPessoaEmail((PessoaEmail[]) lstPessoaEmail.toArray(new PessoaEmail[lstPessoaEmail.size()]));
    }

    private void shTipoPessoa() {
        if (rdbFisica.isSelected()) {
            lblCpfCnpj.setText("CPF:");
            lblRG.setVisible(true);
            txtRG.setVisible(true);
        } else {
            lblCpfCnpj.setText("CNPJ:");
            lblRG.setVisible(false);
            txtRG.setVisible(false);
            txtRG.setText(null);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSexo = new javax.swing.ButtonGroup();
        btnGrpTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        pnlTipoPessoa = new javax.swing.JPanel();
        rdbFisica = new javax.swing.JRadioButton();
        rdbJuridica = new javax.swing.JRadioButton();
        lblCpfCnpj = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        pnlSexo = new javax.swing.JPanel();
        rdbFeminino = new javax.swing.JRadioButton();
        rdbMasculino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTelefone = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEndereco = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmail = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAddEndereco = new javax.swing.JButton();
        btnAdicionarTelefone = new javax.swing.JButton();
        btnAdicionarEmail = new javax.swing.JButton();

        jLabel1.setText("Nome:");

        btnGrpTipo.add(rdbFisica);
        rdbFisica.setSelected(true);
        rdbFisica.setText("Pessoa Física");
        rdbFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFisicaActionPerformed(evt);
            }
        });

        btnGrpTipo.add(rdbJuridica);
        rdbJuridica.setText("Pessoa Jurídica");
        rdbJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTipoPessoaLayout = new javax.swing.GroupLayout(pnlTipoPessoa);
        pnlTipoPessoa.setLayout(pnlTipoPessoaLayout);
        pnlTipoPessoaLayout.setHorizontalGroup(
            pnlTipoPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbJuridica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTipoPessoaLayout.setVerticalGroup(
            pnlTipoPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdbJuridica)
                .addComponent(rdbFisica))
        );

        lblCpfCnpj.setText("CPF:");

        lblRG.setText("RG:");

        btnGrpSexo.add(rdbFeminino);
        rdbFeminino.setText("Feminino");

        btnGrpSexo.add(rdbMasculino);
        rdbMasculino.setSelected(true);
        rdbMasculino.setText("Masculino");

        jLabel10.setText("Sexo:");

        javax.swing.GroupLayout pnlSexoLayout = new javax.swing.GroupLayout(pnlSexo);
        pnlSexo.setLayout(pnlSexoLayout);
        pnlSexoLayout.setHorizontalGroup(
            pnlSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbFeminino)
                .addGap(12, 12, 12))
        );
        pnlSexoLayout.setVerticalGroup(
            pnlSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdbMasculino)
                .addComponent(rdbFeminino)
                .addComponent(jLabel10))
        );

        jLabel12.setText("Data Nascimento:");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tblTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Telefone", "PessoaTelefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTelefone);
        if (tblTelefone.getColumnModel().getColumnCount() > 0) {
            tblTelefone.getColumnModel().getColumn(2).setMinWidth(0);
            tblTelefone.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblTelefone.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        tblEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Endereço", "PessoaEndereco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEndereco);
        if (tblEndereco.getColumnModel().getColumnCount() > 0) {
            tblEndereco.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblEndereco.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblEndereco.getColumnModel().getColumn(2).setMinWidth(0);
            tblEndereco.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblEndereco.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        tblEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "E-mail", "PessoaEmail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblEmail);
        if (tblEmail.getColumnModel().getColumnCount() > 0) {
            tblEmail.getColumnModel().getColumn(1).setMinWidth(0);
            tblEmail.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblEmail.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        jLabel2.setText("Endereço:");

        jLabel7.setText("E-mail:");

        jLabel13.setText("Telefone:");

        btnAddEndereco.setText("Adicionar");

        btnAdicionarTelefone.setText("Adicionar");
        btnAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTelefoneActionPerformed(evt);
            }
        });

        btnAdicionarEmail.setText("Adicionar");
        btnAdicionarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpfCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(pnlSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddEndereco)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                .addComponent(btnAdicionarTelefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdicionarEmail))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(pnlTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCnpj)
                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRG)
                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13)
                    .addComponent(btnAdicionarTelefone)
                    .addComponent(btnAddEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnAdicionarEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdbFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFisicaActionPerformed
        shTipoPessoa();
    }//GEN-LAST:event_rdbFisicaActionPerformed

    private void rdbJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbJuridicaActionPerformed
        shTipoPessoa();
    }//GEN-LAST:event_rdbJuridicaActionPerformed

    private void btnAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelefoneActionPerformed
        FrmPessoaTelefone frm = new FrmPessoaTelefone(null, true);
        frm.setVisible(true);
        if (frm.getPessoaTelefone()!= null) {
            lstPessoaTelefone.add(frm.getPessoaTelefone());
            loadTblPessoaTelefone();
        }
    }//GEN-LAST:event_btnAdicionarTelefoneActionPerformed

    private void btnAdicionarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEmailActionPerformed
        FrmPessoaEmail frm = new FrmPessoaEmail(null, true);
        frm.setVisible(true);
        if (frm.getPessoaEmail() != null) {
            lstPessoaEmail.add(frm.getPessoaEmail());
            loadTblPessoaEmail();
        }
    }//GEN-LAST:event_btnAdicionarEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEndereco;
    private javax.swing.JButton btnAdicionarEmail;
    private javax.swing.JButton btnAdicionarTelefone;
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.ButtonGroup btnGrpTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblRG;
    private javax.swing.JPanel pnlSexo;
    private javax.swing.JPanel pnlTipoPessoa;
    private javax.swing.JRadioButton rdbFeminino;
    private javax.swing.JRadioButton rdbFisica;
    private javax.swing.JRadioButton rdbJuridica;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JTable tblEmail;
    private javax.swing.JTable tblEndereco;
    private javax.swing.JTable tblTelefone;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    // End of variables declaration//GEN-END:variables
}
